# Use babel to parse ES6
# http://eslint.org/docs/user-guide/configuring#specifying-parser
parser: babel-eslint

# Define global variables for the following environments
# http://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es6: true

# Rules
# http://eslint.org/docs/rules/
rules:

  # Possible errors
  # http://eslint.org/docs/rules/#possible-errors
  comma-dangle: error
  no-cond-assign: error
  no-console: error
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations: [error, both]
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-unexpected-multiline: error
  no-unreachable: error
  use-isnan: error
  valid-jsdoc: error
  valid-typeof: error

  # Best Practices
  # http://eslint.org/docs/rules/#best-practices
  accessor-pairs: error
  complexity: [error, 10]
  consistent-return: error
  curly: error
  default-case: error
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: error
  no-alert: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-empty-pattern: error
  no-eval: error
  no-extra-bind: error
  no-fallthrough: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: error
  no-redeclare: error
  no-return-assign: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  radix: [error, as-needed]
  vars-on-top: error
  wrap-iife: error
  yoda: error

  # Variables
  # http://eslint.org/docs/rules/#variables
  init-declarations: error
  no-delete-var: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undefined: error
  no-unused-vars: error
  no-use-before-define: error

  # Node.js and CommonJS
  handle-callback-err: error
  no-path-concat: error

  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  array-bracket-spacing: error
  block-spacing: error
  brace-style: [error, stroustrup, {allowSingleLine: true}]
  camelcase: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  func-names: error
  func-style: [error, expression, {allowArrowFunctions: true}]
  indent: [error, 2]
  key-spacing: error
  keyword-spacing: error
  linebreak-style: error
  lines-around-comment:
    - error
    - {
    beforeLineComment: true,
    allowBlockStart: true,
    allowObjectStart: true,
    allowArrayStart: true
    }
  max-depth: error
  max-len: [error, {ignoreUrls: true}]
  max-nested-callbacks: [error, 3]
  max-params: [error, 4]
  max-statements: error
  max-statements-per-line: error
  new-cap: error
  new-parens: error
  newline-after-var: error
  newline-before-return: error
  newline-per-chained-call: [error, {ignoreChainWithDepth: 3}]
  no-array-constructor: error
  no-bitwise: error
  no-continue: error
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines: [error, {max: 2, maxBOF: 0, maxEOF: 1}]
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  no-plusplus: error
  no-spaced-func: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing: error
  one-var: [error, never]
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: [error, never]
  quote-props: error
  quotes: [error, single, {avoidEscape: true, allowTemplateLiterals: true}]
  require-jsdoc: warn
  semi: [error, never]
  sort-imports: [warn, {ignoreCase: true}]
  sort-vars: [warn, {ignoreCase: true}]
  space-before-blocks: error
  space-before-function-paren: [error, never]
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  wrap-regex: error

  # ECMAScript 6
  # http://eslint.org/docs/rules/#ecmascript-6
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-this-before-super: error
  no-useless-constructor: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: [error, {allowNamedFunctions: true}]
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  template-curly-spacing: error
  yield-star-spacing: error
